# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be4de67ebde5d57c9cc2404911a86c1f02b386d906c1725b8c2a2dfdcf454a8279639995adc2f5991fd1a4169e4d3a8b835c80fac209133103d86e8223d482f

test:
  secret_key_base: 78bde9144abc3cf2c4880ccd537e3395a63d3700cb290d9b6a38e907670416924555cdb548a9a5f8cda360f1c331dac64c1a16131c55baaba15d841a59b3e5d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
